student/D33102 shiziming/lab3/BBB/BBB/urls.py
from django.contrib import admin
from django.urls import path, include
from racer import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grouplist/',views.group_list),
    path('groupdeta/<int:pk>/',views.group_deta.as_view()),
    path('creategroup/',views.create_group),
    path('createracer/',views.create_racer),
    path('updetaracer/<int:pk>/',views.racerUpdateView.as_view()),
    path('deleracer/<int:pk>/',views.delete_racer),
    path('accounts/', include('allauth.urls')),
    path('No1/<int:pk>/', views.car_type.as_view()),
    path('up/<int:pk>/', views.AuthorCreate2.as_view()),
    path('create/', views.AuthorCreate.as_view()),
    path('delete_result/<int:pk>/', views.delete_result),
    path('result_list/', views.result_list),
]

student/D33102 shiziming/lab3/BBB/racer/models.py
from django.db import models

class Match(models.Model):
    locatoin=models.CharField(max_length=50)
    time=models.DateTimeField()

class comments(models.Model):
    comment=models.CharField(max_length=100)
    data=models.DateTimeField()
    commentator=models.CharField(max_length=50)
    ID_Match=models.ForeignKey(Match,null=True,blank=True,on_delete=models.SET_NULL)

class round(models.Model):
    Number_round=models.CharField(max_length=20)
    ID_Match = models.ForeignKey(Match, null=True, blank=True, on_delete=models.SET_NULL)

class group(models.Model):
    Group_name=models.CharField(max_length=50)
    ID_round=models.ForeignKey(round, null=True, blank=True, on_delete=models.SET_NULL)

class Racer(models.Model):
    racer_name=models.CharField(max_length=50)
    Introduction=models.CharField(max_length=100)
    rank=models.CharField(max_length=20)
    ID_group=models.ForeignKey(group, null=True, blank=True, on_delete=models.SET_NULL)

class Racing_car(models.Model):
    type_list=(('M','motorcycle'),('ort','Off road truck'),('SUV','offroad racing'))
    Vehicle_type=models.CharField(max_length=3,choices=type_list)
    ID_racer=models.ForeignKey(Racer, null=True, blank=True, on_delete=models.SET_NULL)

class result(models.Model):
    result=models.CharField(max_length=20)
    time_cost = models.CharField(max_length=20)
    ID_racer = models.ForeignKey(Racer, null=True, blank=True, on_delete=models.SET_NULL)
    ID_Match = models.ForeignKey(Match, null=True, blank=True, on_delete=models.SET_NULL)

student/D33102 shiziming/lab3/BBB/racer/forms.py
from django import forms
from .models import group,Racer,Racing_car

class racerForm(forms.ModelForm):
    class Meta:
        model = Racer
        fields = ('racer_name','Introduction','rank','ID_group')

class groupForm(forms.ModelForm):
    class Meta:
        model = group
        fields = ('Group_name',)

student/D33102 shiziming/lab3/BBB/racer/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .forms import racerForm,groupForm
from .models import Match,comments,round,group,Racer,Racing_car,result
from django.views.generic.edit import UpdateView,CreateView

def group_list(request):
  model1 = group.objects.filter().all
  model2 = result.objects.filter().all

  return render(request,"group_list.html",context=locals())

class group_deta(DetailView):
    model = group
    template_name = "group_deta.html"

def create_group(request):
    context = {}
    form = groupForm(request.POST or None)
    if form.is_valid():
        form.save()
    context['form'] = form
    return render(request, "creategroup.html", context)

def create_racer(request):
    context = {}
    form = racerForm(request.POST or None)
    if form.is_valid():
        form.save()
    context['form'] = form
    return render(request, "createracer.html", context)

class racerUpdateView(UpdateView):
  model = Racer
  fields = ('racer_name','Introduction','rank','ID_group')
  success_url = "/grouplist/"
  template_name = 'modifyracer.html'

def delete_racer(respons,pk):
    d = Racer.objects.get(pk=pk)
    d.delete()
    return HttpResponse("Deleted")

class car_type(UpdateView):
  model = Racing_car
  fields = ('Vehicle_type',)
  success_url = "/grouplist/"
  template_name ="First_one.html"

class AuthorCreate(CreateView):
    model = result
    fields = ['result','ID_racer','ID_Match','time_cost']
    template_name = "create_result.html"
    success_url = "/grouplist/"

class AuthorCreate2(UpdateView):
    model = result
    fields = ['result','ID_racer','ID_Match','time_cost']
    template_name = "up_data_result.html"
    success_url = "/grouplist/"

def delete_result(respons,pk):
    d = result.objects.get(pk=pk)
    d.delete()
    return HttpResponseRedirect('/grouplist/')

def result_list(request):
  model2 = result.objects.filter().all

  return render(request,"result_list.html",context=locals())

student/D33102 shiziming/lab3/BBB/templates/First_one.html
<!-- publisher_form.html -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>updata</title>
</head>

<body>
  <form method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save">
  </form>
</body>

</html>

student/D33102 shiziming/lab3/BBB/templates/create_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

student/D33102 shiziming/lab3/BBB/templates/creategroup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
    <a href="/grouplist/">Get Back</a>
</form>
</body>
</html>

student/D33102 shiziming/lab3/BBB/templates/createracer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
    <a href="/grouplist/">Get Back</a>
</form>
</body>
</html>

student/D33102 shiziming/lab3/BBB/templates/group_deta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>group_deta</title>
</head>
<body>
<h2>{{group.Group_name}}</h2>
<h2>Racer:</h2>
{% for r in group.racer_set.all %}
    <hr>
    <li>Name : {{r.racer_name}}</li>
    <li>Introduction : {{r.Introduction}} </li>
    <li>rank : {{r.rank}}</li>
    <h3>racing car : </h3>
{% for rc in r.racing_car_set.all %}
<li>{{forloop.counter}} : {{rc.Vehicle_type}} <button><a href='/No1/{{rc.id}}/'>Up</a></button></li>
{% endfor %}
    <button><a href="/updetaracer/{{r.id}}/">Updeta</a></button>
    <button><a href="/deleracer/{{r.id}}/">Delet</a></button>
    <hr>
{% endfor %}

<p><a href="/createracer/">createracer</a></p>
<p><a href="/grouplist/">Get Back</a></p>
</body>
</html>

student/D33102 shiziming/lab3/BBB/templates/group_list.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>group_list</title>
</head>
<body>
<h1><strong>Group List</strong></h1>
<hr>
{% for g in model1 %}
<p>Group name:<a href="/groupdeta/{{g.id}}/">{{g.Group_name}}</a></p>
{% endfor %}
<hr>
<p><button><a href="/creategroup/">create</a></button></p>
<p><button><a href="/result_list/">Result Tabel</a></button></p>

</body>
</html>

student/D33102 shiziming/lab3/BBB/templates/modifyracer.html
<!-- publisher_form.html -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>updata</title>
</head>

<body>
  <form method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save">
  </form>
</body>

</html>

student/D33102 shiziming/lab3/BBB/templates/result_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result Tabel</title>
</head>
<body>
<div class="">
<table style="width: 1500px;margin: auto">
    <caption>result table</caption>

    <tr>
        <td width="300" height="80">Group_name</td>
        <td width="300" height="80">racer_name</td>
        <td width="300" height="80">Macth</td>
        <td width="300" height="80">Ranking</td>
        <td width="300" height="80">time_cost</td>
        <td width="300" height="80">Add</td>
        <td width="300" height="80">Updata</td>
        <td width="300" height="80">Delet</td>
    </tr>
    {% for r in model2%}
    <tr>
        <td width="300" height="80">{{r.ID_racer.ID_group.Group_name}}</td>
        <td width="300" height="80">{{r.ID_racer.racer_name}}</td>
        <td width="300" height="80">{{r.ID_Match.id}}</td>
        <td width="300" height="80">{{r.result}}</td>
        <td width="300" height="80">{{r.time_cost}}</td>
        <td width="300" height="80"><button><a href="/create/">add</a></button></td>
        <td width="300" height="80"><button><a href="/up/{{ r.id }}/">Up</a></button></td>
        <td width="300" height="80"><button><a href="/delete_result/{{r.id}}/">Del</a></button></td>
    {% empty %}
        <td colspan="6">None</td>
        <td width="300" height="80"><button><a href="/create/">add</a></button></td>
    {% endfor %}
    </tr>
</table>
</div>
</body>
</html>

student/D33102 shiziming/lab3/BBB/templates/up_data_result.html
<!-- publisher_form.html -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>updata</title>
</head>

<body>
  <form method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save">
  </form>
</body>

</html>